### ISSUE TITLE
Error in ISO 2020, section 3.13 (pattern)

### ISSUE THREAD

**Issue by dmj** [Schematron/schematron-enhancement-proposals#18] opened 2021-07-28 18:54 UTC
Section 3.13 should read:

> **ordered** collection of rules (3.18) with an optional identifier and ancillary information

The order of rules matters.

**Comment by rjelliffe** [comment] 2022-07-08 10:56
This ambiguity needs to be clarified, but I suggest that replacing "unordered" with "ordered" perpetuates the ambiguity, not resolves it.

So better text might be:

collection of rules (3.18) with an optional identifier and ancillary information. Patterns of a schema do not have a defined order.

and similarly add the equivalent for assert, report, diagnostic, property.  For rule, check it is clear:  Rules in a pattern are lexically ordered.

---------
DISCUSSION

The issue is whether "unordered" refers to the pattern (i.e. it has no order with its siblings), or to the rules, or so the collection. An example of this usage might be 

  Trump: orange former president

The orange does not refer to his presidency but to Trump. E.g.  Trump is orange, Trump is former president, therefore Trump orange former president.

In markup, we might say both that "items in numeric lists are ordered" and "a numeric list is ordered". In fact, "ordered lists" are a thing <ol>, of course.  So the appropriate correction is no "unordered" -> "ordered" is wrong because the constraint here is supposed to be the one between patterns not the one between rules.

**Comment by AndrewSales** [comment] 2023-04-22 17:23
For `pattern`, "unordered" is removed from latest draft, and a note added that they do not have a defined order.
I will leave this issue open on the grounds it may relate to other elements, as @rjelliffe mentions above, and which may be attended to similarly as drafting work proceeds.

**Comment by AndrewSales** [comment] 2024-02-23 11:31
#68 has the gist of other potential changes to the text, so closing.

**Closed by AndrewSales** 2024-02-23 11:31 UTC
Labels: erratum, element pattern, 2025
